name: Terraform Apply

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: [self-hosted, my-runner]
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v1

      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5

      - name: Get branch diff
        id: gitdiff
        run: |
          dirs=$(git diff master^ master --name-only | grep -v '^.github/' | xargs dirname  | uniq)
          echo "::set-output name=dir::$dir"

      # Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Init"
        if: steps.gitdiff.outputs.dir != ''
        run: |
              if [[ steps.gitdiff.outputs.dir != "" ]];then
              dirs=$(git diff master^ master --name-only | grep -v '^.github/' | xargs dirname  | uniq)
              for dir in $dirs
              do
              cd ${GITHUB_WORKSPACE}/$dir && terraform init -input=false
              done
              fi


      # The id value is used for reference in the comment step via "steps.plan.outputs.stdout"
      # Note: Color is disabled to prevent messy characters from appearing in the pull request comment
      - name: "Run - Terraform Apply"
        if: steps.gitdiff.outputs.dir != ''
        continue-on-error: true
        id: apply
        run: |
            echo ${{steps.gitdiff.outputs.dir}}
            if [[ steps.gitdiff.outputs.dir != "" ]];then
            dirs=$(git diff master^ master --name-only | grep -v '^.github/' | xargs dirname  | uniq)
            for dir in $dirs
            do
            cd ${GITHUB_WORKSPACE}/$dir && terraform apply -input=false -no-color -auto-approve > tfapply 2>&1 && echo "<details><summary>$dir</summary>" >>  ${GITHUB_WORKSPACE}/tfapply || { echo '::set-output name=TF_APPLY_STATUS::fail'; echo "<details><summary>Error in $dir terraform apply</summary>" >>  ${GITHUB_WORKSPACE}/tfapply; }
            cat >> ${GITHUB_WORKSPACE}/tfapply <<EOF

            \`\`\`

            `cat tfapply`

            \`\`\`

            </details>

            EOF
            done
            fi

      - name: Read tfapply
        id: data
        continue-on-error: true
        uses: juliangruber/read-file-action@v1
        with:
          path: ./tfapply

      - uses: actions/github-script@0.9.0
        if: ${{ github.event_name == 'pull_request' }}
        env:
          APPLY: "${{ steps.data.outputs.content }}"
        continue-on-error: true

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Terraform APPLY outputs

            ${process.env.APPLY}

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\` Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Plan Status
        run: |
          if [[ "${{ steps.palm.outputs.TF_APPLY_STATUS }}" == "fail" ]];then
          exit 1
          else
          true
          fi
