name: Run on PR comment

on:
  issue_comment:
    types:
    - created

jobs:
  runs-on: ubuntu-latest
  if: ${{ github.event.issue.pull_request }}
  steps:
      - name: Execute for pull request comments only
        if: github.event.issue.pull_request
        run: echo "This is a pull request comment event"
