
name: Create terraform plan

on:
  push:
    branches:
      - staging

jobs:
  plan:
    runs-on: self-hosted
    name: Create a plan for an example terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
          - uses: actions/checkout@v2
          - uses: hashicorp/setup-terraform@v1

          - name: Terraform execute
            id: init
            script: |
              dirs=$(git diff master ${GITHUB_REF#refs/heads/} --name-only | grep -v '^.github/' | xargs dirname  | uniq)
              for dir in $dirs
              do
              terraform init
              terraform plan
              done
